In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("dataset - Sheet1.csv")

In [3]:
df.head()

Predicted Class  Actual Class
0                0             0
1                0             0
2                1             0
3                0             0
4                0             0

In [4]:
df.size

320

In [5]:
df.shape

(160, 2)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Predicted Class  160 non-null    int64
 1   Actual Class     160 non-null    int64
dtypes: int64(2)
memory usage: 2.6 KB


In [27]:
a=df['Predicted Class'].unique()
a

array([0, 1, 2, 3], dtype=int64)

In [6]:
tp=df[df['Actual Class'] == df['Predicted Class']]

In [7]:
tp.head()

Predicted Class  Actual Class
0                0             0
1                0             0
3                0             0
4                0             0
8                0             0

In [9]:
tp.shape

(121, 2)

In [10]:
#Therefore total number of correct prediction is 121 out of 160

# 2.a

In [14]:
Accuracy=121/165
Accuracy

0.7333333333333333

In [28]:
tp0=df[(df['Actual Class'] ==0) & (df['Predicted Class']==0)]

In [29]:
tp0.shape

(33, 2)

In [30]:
tp1=df[(df['Actual Class'] ==1) & (df['Predicted Class']==1)]

In [31]:
tp1.shape

(32, 2)

In [32]:
tp2=df[(df['Actual Class'] ==2) & (df['Predicted Class']==2)]
tp2.shape

(29, 2)

In [33]:
tp3=df[(df['Actual Class'] ==3) & (df['Predicted Class']==3)]
tp3.shape

(27, 2)

In [34]:
tp01=df[(df['Actual Class'] ==0) & (df['Predicted Class']==1)]
tp01.shape

(8, 2)

In [36]:
tp02=df[(df['Actual Class'] ==0) & (df['Predicted Class']==2)]
tp02.shape

(4, 2)

In [37]:
tp03=df[(df['Actual Class'] ==0) & (df['Predicted Class']==3)]
tp03.shape

(4, 2)

In [39]:
tp10=df[(df['Actual Class'] ==1) & (df['Predicted Class']==0)]
print(tp10.shape)
tp12=df[(df['Actual Class'] ==1) & (df['Predicted Class']==2)]
print(tp12.shape)
tp13=df[(df['Actual Class'] ==1) & (df['Predicted Class']==3)]
print(tp13.shape)

(1, 2)
(3, 2)
(0, 2)


In [40]:
tp20=df[(df['Actual Class'] ==2) & (df['Predicted Class']==0)]
print(tp10.shape)
tp22=df[(df['Actual Class'] ==2) & (df['Predicted Class']==1)]
print(tp22.shape)
tp23=df[(df['Actual Class'] ==2) & (df['Predicted Class']==3)]
print(tp23.shape)

(1, 2)
(2, 2)
(6, 2)


In [41]:
tp30=df[(df['Actual Class'] ==3) & (df['Predicted Class']==0)]
print(tp30.shape)
tp31=df[(df['Actual Class'] ==3) & (df['Predicted Class']==1)]
print(tp31.shape)
tp32=df[(df['Actual Class'] ==3) & (df['Predicted Class']==2)]
print(tp32.shape)

(2, 2)
(3, 2)
(3, 2)


# 2.b

# Here is the confusion matrix

# 2.a

In [45]:
overall_accuracy=(33+32+29+27)/160
overall_accuracy

0.75625

In [46]:
121/160

0.75625

In [47]:
class0_accuracy=33/(33+8+4+4)
class0_accuracy

0.673469387755102

In [48]:
class1_accuracy=32/(1+32+3+0)
class1_accuracy

0.8888888888888888

In [49]:
class2_accuracy=29/(1+2+29+6)
class2_accuracy

0.7631578947368421

In [50]:
class3_accuracy=27/(2+3+3+27)
class3_accuracy

0.7714285714285715

# 2.c

class0

In [ ]:
            predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   1   2   29  6
           
           3   2   3   3   27

In [51]:
tp0=33
tn0=32+3+2+3+29+6+3+27
fp0=1+1+2
fn0=8+4+4


we have all the necessary metrics for class 0 from the confusion matrix, now we can calculate the performance measures for class 0.

In [57]:
precision0=tp0/(tp0+fp0)
print(precision0)
recall0=tp0/(tp0+fn0)
print(recall0)

0.8918918918918919
0.673469387755102


class1

In [56]:
              predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   1   2   29  6
           
           3   2   3   3   27

IndentationError: unexpected indent (<ipython-input-56-1f6804643b41>, line 2)

In [59]:
tp1=32
tn1=33+4+4+1+2+29+6+27+3
fp1=8+2+3
fn1=1+3+0

In [60]:
precision1=tp1/(tp1+fp1)
print(precision1)
recall1=tp1/(tp1+fn1)
print(recall1)

0.7111111111111111
0.8888888888888888


class2

In [63]:
tp2=29
tn2=33+8+4+1+32+0+2+3+27
fp2=4+3+3
fn2=1+2+6

In [64]:
precision2=tp2/(tp2+fp2)
print(precision2)
recall2=tp2/(tp2+fn2)
print(recall2)

0.7435897435897436
0.7631578947368421


class3

In [65]:
              predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   1   2   29  6
           
           3   2   3   3   27

IndentationError: unexpected indent (<ipython-input-65-1f6804643b41>, line 2)

In [66]:
tp3=27
tn3=33+8+4+1+32+3+1+2+29
fp3=4+0+6
fn3=2+3+3

In [67]:
precision3=tp3/(tp3+fp3)
print(precision3)
recall3=tp3/(tp3+fn3)
print(recall3)

0.7297297297297297
0.7714285714285715


# Macro_avg

macro-avg is mean average macro-avg is mean average precision/recall of all classes.

In [70]:

macro_avg_precision=(precision0+precision1+precision2+precision3)/4
macro_avg_precision

0.7690806190806191

In [72]:
macro_avg_recall=(recall0+recall1+recall2+recall3)/4
macro_avg_recall

0.7742361857023511

# Weighted_avg

The weights for each class are the total number of samples of that class

In [74]:
weighted_avg_precision=(precision0*49+precision1*36+precision2*38+precision3*35)/(49+36+38+35)
weighted_avg_precision

0.7791117310104652

In [75]:
weighted_avg_recall=(recall0*49+recall1*36+recall2*38+recall3*35)/(49+36+38+35)
weighted_avg_recall

0.7658227848101266

# F-1 Score

In [76]:
class0_f1=2*(precision0*recall0)/(precision0+recall0)
class0_f1

0.7674418604651163

In [77]:
class1_f1=2*(precision1*recall1)/(precision1+recall1)
class1_f1

0.7901234567901234

In [78]:
class2_f1=2*(precision2*recall2)/(precision2+recall2)
class2_f1

0.7532467532467534

In [79]:
class3_f1=2*(precision3*recall3)/(precision3+recall3)
class3_f1

0.75

# 2.e

In [82]:
class0_type_1=fp0/(fp0+tn0)
print(class0_type_1)
class0_type_2=fn0/(fn0+tp0)
print(class0_type_2)

0.03669724770642202
0.32653061224489793


In [83]:
class1_type_1=fp1/(fp1+tn1)
print(class1_type_1)
class1_type_2=fn1/(fn1+tp1)
print(class1_type_2)

0.10655737704918032
0.1111111111111111


In [84]:
class2_type_1=fp2/(fp2+tn2)
print(class2_type_1)
class2_type_2=fn2/(fn2+tp2)
print(class2_type_2)

0.08333333333333333
0.23684210526315788


In [85]:
class3_type_1=fp3/(fp3+tn3)
print(class3_type_1)
class3_type_2=fn3/(fn3+tp3)
print(class3_type_2)

0.08130081300813008
0.22857142857142856


# 2.f

In [98]:
X = df['Actual Class'].values.reshape(-1,1)
X.ndim
#X=X.reshape(-1,1)
#y = df['Predicted Class']


2

In [103]:
X = df['Actual Class'].values.reshape(-1,1)

y = df['Predicted Class']
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
svc = SVC(kernel='rbf', C=1).fit(X_train, y_train)
y_pred = svc.predict(X_test)

#importing confusion matrix
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

#importing accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))


print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Class 0','Class 1', 'Class 2', 'Class 3']))

Confusion Matrix

[[ 6  0  1  0]
 [ 1  9  1  1]
 [ 1  1 10  1]
 [ 2  0  1  5]]

Accuracy: 0.75

Macro Precision: 0.75
Macro Recall: 0.75
Macro F1-score: 0.74

Weighted Precision: 0.77
Weighted Recall: 0.75
Weighted F1-score: 0.75

Classification Report

              precision    recall  f1-score   support

     Class 0       0.60      0.86      0.71         7
     Class 1       0.90      0.75      0.82        12
     Class 2       0.77      0.77      0.77        13
     Class 3       0.71      0.62      0.67         8

    accuracy                           0.75        40
   macro avg       0.75      0.75      0.74        40
weighted avg       0.77      0.75      0.75        40



In [102]:
X_train.shape

(120, 1)

In [ ]:
print(y_train)

# Comparision Table between sklearn output and standard output

In [105]:
Camparison Report                                                 



              precision_sklearn/standard   recall_sklearn/standard  f1-score_sklearn/standard    

     Class 0       0.60/.89                          0.86/.67                      0.71/.76        
     Class 1       0.90/.71                          0.75/.88                      0.82/.79        
     Class 2       0.77/.74                         0.77/.76                      0.77/.75        
     Class 3       0.71/.72                         0.62/.77                      0.67/.75         

    accuracy                           0.75/.75        
   macro avg       0.75/.76      0.75/.77      0.74/.74        
weighted avg       0.77/.77      0.75/.76      0.75/.75        

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 7)