In [1]:
#import some basic library
import numpy as np
import pandas as pd 

# Q-1

# Evaluation metrics

# 1-Log loss

This classification metric based on probabilities.

It measures the performance of a classification model where the prediction result into a probability value between  one / zero. 
Log loss increases as the predicted probability diverge from the actual label. 
The goal of  machine learning model to minimize this value. 
As such, smaller log loss better will the model,a perfect model having a log loss of zero.

Implementation part use:
    accuracy = log_loss(y_test, pred)
    #print("Logloss: %.2f" % (accuracy))

Lower the value ,better will be the model

# 2-Jaccard Index

Let’s understandan example.
labeled test , labels    as –y =  [0,0,0,0,0,1,1,1,1,1]
our model has predicted  as –y1 = [1,1,0,0,0,1,1,1,1,1]

Jaccard Index / Jaccard similarity coefficient is a statistic used in understanding the similarities between sample sets.
The measurement emphasizes the similarity between finite sample sets and  formally defined as the size of the intersection divided by the size of the union of the two labeled sets

we can see that the intersection of the two sets is equal to 8 (since eight values are predicted correctly) and the union is 10 + 10–8 = 12. 
So, the Jaccard index gives the accuracy –: 66 %(8/12)



# 3- Gini Coefficient

The Gini coefficient/Gini Index is a popular metric for imbalanced class values. 
The coefficient ranges from 0 to 1 where 0 represents perfect equality and 1 represents perfect inequality. 
Here, if the value of an index is higher, then the data will be more dispersed.

Gini coefficient can be computed from the area under the ROC curve using the following formula:

Gini Coefficient = (2 * ROC_curve) — 1

In [4]:
#load the dataset
df=pd.read_csv("dataset - Sheet1.csv")

In [5]:
df.head()

Predicted Class  Actual Class
0                0             0
1                0             0
2                1             0
3                0             0
4                0             0

In [6]:
df.size

320

In [7]:
df.shape

(160, 2)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Predicted Class  160 non-null    int64
 1   Actual Class     160 non-null    int64
dtypes: int64(2)
memory usage: 2.6 KB


In [9]:
#find the number of multiclass
a=df['Predicted Class'].unique()
a

array([0, 1, 2, 3], dtype=int64)

In [10]:
#true positive
tp=df[df['Actual Class'] == df['Predicted Class']]

In [11]:
tp.head()

Predicted Class  Actual Class
0                0             0
1                0             0
3                0             0
4                0             0
8                0             0

In [12]:
tp.shape

(121, 2)

In [13]:
#Therefore total number of correct prediction is 121 out of 160

# 2.a

In [14]:
#accuracy
Accuracy=121/160
Accuracy

0.75625

In [15]:
#true positive for class 0
tp0=df[(df['Actual Class'] ==0) & (df['Predicted Class']==0)]
tp0.shape

(33, 2)

In [16]:
#true positive for class 1
tp1=df[(df['Actual Class'] ==1) & (df['Predicted Class']==1)]
tp1.shape

(32, 2)

In [17]:
# true positive for class 2
tp2=df[(df['Actual Class'] ==2) & (df['Predicted Class']==2)]
tp2.shape

(29, 2)

In [18]:
# true positive fro class 3
tp3=df[(df['Actual Class'] ==3) & (df['Predicted Class']==3)]
tp3.shape

(27, 2)

In [19]:
# actual class 0 predictive as class 1,2,3
tp01=df[(df['Actual Class'] ==0) & (df['Predicted Class']==1)]
print(tp01.shape)
tp02=df[(df['Actual Class'] ==0) & (df['Predicted Class']==2)]
print(tp02.shape)
tp03=df[(df['Actual Class'] ==0) & (df['Predicted Class']==3)]
print(tp03.shape)

(8, 2)
(4, 2)
(4, 2)


In [20]:
# actual class 1 predictive as class 0,2,3
tp10=df[(df['Actual Class'] ==1) & (df['Predicted Class']==0)]
print(tp10.shape)
tp12=df[(df['Actual Class'] ==1) & (df['Predicted Class']==2)]
print(tp12.shape)
tp13=df[(df['Actual Class'] ==1) & (df['Predicted Class']==3)]
print(tp13.shape)

(1, 2)
(3, 2)
(0, 2)


In [21]:
# actual class 2 predictive as class 0,1,3
tp20=df[(df['Actual Class'] ==2) & (df['Predicted Class']==0)]
print(tp20.shape)
tp22=df[(df['Actual Class'] ==2) & (df['Predicted Class']==1)]
print(tp22.shape)
tp23=df[(df['Actual Class'] ==2) & (df['Predicted Class']==3)]
print(tp23.shape)

(3, 2)
(2, 2)
(6, 2)


In [22]:
# actual class 3 predictive as class 0,1,2
tp30=df[(df['Actual Class'] ==3) & (df['Predicted Class']==0)]
print(tp30.shape)
tp31=df[(df['Actual Class'] ==3) & (df['Predicted Class']==1)]
print(tp31.shape)
tp32=df[(df['Actual Class'] ==3) & (df['Predicted Class']==2)]
print(tp32.shape)

(2, 2)
(3, 2)
(3, 2)


# By using the above output of the cell, we can draw the confusion matrix.
# 2.b



# 2.a

In [23]:
#overall accuracy
overall_accuracy=(33+32+29+27)/160
overall_accuracy

0.75625

In [24]:
#class 0 accuracy
class0_accuracy=33/(33+8+4+4)
class0_accuracy

0.673469387755102

In [25]:
# class 1 accuracy
class1_accuracy=32/(1+32+3+0)
class1_accuracy

0.8888888888888888

In [26]:
# class 2 accuracy
class2_accuracy=29/(3+2+29+6)
class2_accuracy

0.725

In [27]:
# class 3 accuracy
class3_accuracy=27/(2+3+3+27)
class3_accuracy

0.7714285714285715

# 2.c

class0

            predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

In [30]:
tp0=33
tn0=32+3+2+3+29+6+3+27
fp0=1+3+2
fn0=8+4+4


# we have all the necessary metrics for class 0 from the confusion matrix, now we can calculate the performance measures for class 0.

In [31]:
# precision and recall of class 0
precision0=tp0/(tp0+fp0)
print(precision0)
recall0=tp0/(tp0+fn0)
print(recall0)

0.8461538461538461
0.673469387755102


# class1

              predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

In [33]:
tp1=32
tn1=33+4+4+3+2+29+6+27+3
fp1=8+2+3
fn1=1+3+0

In [34]:
# precision and recall of class 1
precision1=tp1/(tp1+fp1)
print(precision1)
recall1=tp1/(tp1+fn1)
print(recall1)

0.7111111111111111
0.8888888888888888


# class2

In [35]:
tp2=29
tn2=33+8+4+1+32+0+2+3+27
fp2=4+3+3
fn2=3+2+6

In [36]:
# precision and recall of class 2
precision2=tp2/(tp2+fp2)
print(precision2)
recall2=tp2/(tp2+fn2)
print(recall2)

0.7435897435897436
0.725


# class3

In [ ]:
              predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

In [37]:
tp3=27
tn3=33+8+4+1+32+3+3+2+29
fp3=4+0+6
fn3=2+3+3

In [38]:
# precision and recall of class 3
precision3=tp3/(tp3+fp3)
print(precision3)
recall3=tp3/(tp3+fn3)
print(recall3)

0.7297297297297297
0.7714285714285715


# Macro_avg

macro-avg is mean average macro-avg is mean average precision/recall of all classes.

In [39]:
macro_avg_precision=(precision0+precision1+precision2+precision3)/4
macro_avg_precision

0.7576461076461076

In [40]:
macro_avg_recall=(recall0+recall1+recall2+recall3)/4
macro_avg_recall

0.7646967120181406

# Weighted_avg

The weights for each class are the total number of samples of that class

In [41]:
weighted_avg_precision=(precision0*49+precision1*36+precision2*38+precision3*35)/(49+36+38+35)
weighted_avg_precision

0.7649271472056283

In [42]:
weighted_avg_recall=(recall0*49+recall1*36+recall2*38+recall3*35)/(49+36+38+35)
weighted_avg_recall

0.7566455696202532

# F-1 Score
# 2.d

In [43]:
class0_f1=2*(precision0*recall0)/(precision0+recall0)
class0_f1

0.75

In [44]:
class1_f1=2*(precision1*recall1)/(precision1+recall1)
class1_f1

0.7901234567901234

In [45]:
class2_f1=2*(precision2*recall2)/(precision2+recall2)
class2_f1

0.7341772151898733

In [46]:
class3_f1=2*(precision3*recall3)/(precision3+recall3)
class3_f1

0.75

# 2.e

In [47]:
# type-1 and 2 error of class 0
class0_type_1=fp0/(fp0+tn0)
print(class0_type_1*100)
class0_type_2=fn0/(fn0+tp0)
print(class0_type_2*100)

5.405405405405405
32.6530612244898


In [48]:
# type-1 and 2 error of class 1
class1_type_1=fp1/(fp1+tn1)
print(class1_type_1*100)
class1_type_2=fn1/(fn1+tp1)
print(class1_type_2*100)

10.483870967741936
11.11111111111111


In [49]:
# type-1 and 2 error of class 2
class2_type_1=fp2/(fp2+tn2)
print(class2_type_1*100)
class2_type_2=fn2/(fn2+tp2)
print(class2_type_2*100)

8.333333333333332
27.500000000000004


In [50]:
# type-1 and 2 error of class 3
class3_type_1=fp3/(fp3+tn3)
print(class3_type_1*100)
class3_type_2=fn3/(fn3+tp3)
print(class3_type_2*100)

8.0
22.857142857142858


In [51]:
y_test = df['Actual Class']
y_pred = df['Predicted Class']


#importing confusion matrix
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

#importing accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))


print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Class 0','Class 1', 'Class 2', 'Class 3']))

Confusion Matrix

[[33  8  4  4]
 [ 1 32  3  0]
 [ 3  2 29  6]
 [ 2  3  3 27]]

Accuracy: 0.76

Macro Precision: 0.76
Macro Recall: 0.76
Macro F1-score: 0.76

Weighted Precision: 0.76
Weighted Recall: 0.76
Weighted F1-score: 0.76

Classification Report

              precision    recall  f1-score   support

     Class 0       0.85      0.67      0.75        49
     Class 1       0.71      0.89      0.79        36
     Class 2       0.74      0.72      0.73        40
     Class 3       0.73      0.77      0.75        35

    accuracy                           0.76       160
   macro avg       0.76      0.76      0.76       160
weighted avg       0.76      0.76      0.76       160



# Comparision Table between sklearn output and standard output
# 2.f

In [ ]:
Camparison Report                                                 



              precision_sklearn/standard   recall_sklearn/standard  f1-score_sklearn/standard    

     Class 0       0.85/.85                          0.67/.67                      0.75/.75        
     Class 1       0.71/.71                          0.89/.89                      0.79/.79        
     Class 2       0.74/.74                         0.72/.72                      0.73/.73        
     Class 3       0.73/.73                         0.77/.77                      0.75/.75         

    accuracy                           0.76/.75        
   macro avg       0.76/.76      0.76/.76      0.76/.76        
weighted avg       0.76/.76      0.76/.76      0.76/.76        

# 2-g

In [52]:
#using log loss
#from sklearn.metrics import log_loss
#accuracy = log_loss(y_test, y_pred)
overall_accuracy

0.75625

Refrences:1-https://towardsdatascience.com/confusion-matrix-for-your-multi-class-machine-learning-model-ff9aa3bf7826

2-https://www.kdnuggets.com/2020/05/model-evaluation-metrics-machine-learning.html

# Thank You